### ISSUE TITLE
mongo session store always on localhost

### ISSUE THREAD

**Issue by srouthiau** [gadael/gadael#11]
Session store still on localhost even if config.mongodb.prefix configured

Please change Company.api.js as 

        // the mongostore lock the gracefull stop of the app
        app.session_mongoStore = new mongoStore({
			uri: 'mongodb://' + app.config.mongodb.prefix + app.config.mongodb.dbname,
			collection: 'gadael-sessions'
		});

**Comment by polo2ro** [comment]
Hi, thanks for your contribution, i merged the PR with a minor change, the collection name is now 'sessions'
