### ISSUE TITLE
E-mail not sent

### ISSUE THREAD

**Issue by Almiriad** [gadael/gadael#15]
We have configured Gadael on our server, its based on the latests version of Github.
It runs correctly, accounts can be created, leaves can be planned.

However e-mails are not sent.
We use a Gmail SMTP account as below :
` config.mailtransport = {
         host: 'smtp.gmail.com',
         port: 465,
         secure: true,           // use SSL
         auth: {
             user: 'mail@gmail.com',
             pass: 'password'
         }
     };`

I can't manage to find any logs related to the application that could help me on this problem.
Could you help me on this issue ?
What other information coudl be useful to debug this ?

**Comment by polo2ro** [comment]
Hi,
All sent or errored emails are stored in the database, you can access the error message in the "Message" collection, if nodemailer produce an error message, a "error" property is stored in the message document, otherwise the "infos" property is updated
