### ISSUE TITLE
English Calendar

### ISSUE THREAD

**Issue by vinaykharecha** [gadael/gadael#2]
How to get English calendar in website?
Whenever click on date picker calendar shown is not in English.

**Comment by polo2ro** [comment]
This is probably a bug on my side, because the date picker is from angularstrap http://mgcrea.github.io/angular-strap/#/datepickers and default in english. I will fix this.

**Comment by polo2ro** [comment]
This has been fixed in a recent commit, no version with the fix yet

**Comment by vinaykharecha** [comment]
Thank you @polo2ro; has commit been moved to master?

**Comment by polo2ro** [comment]
Yes
