### ISSUE TITLE
Unable to request recover on Saturdays

### ISSUE THREAD

**Issue by Mika56** [gadael/gadael#20]
Hello,

We're currently trying Gadael and we are stuck by this issue.
When a user creates a new recover request, Saturdays are not available (and Sundays are not available right away too).
Here's a screenshot of the problem:
![2019-10-16_10-53-48](https://user-images.githubusercontent.com/600347/66903790-60233900-f003-11e9-9182-b8d6eff61101.png)
You can see multiple problems on this image:

- Users can't request recover in the past. You can't always plan your extra time, and can need to declare overtime after it happened
  - But users can request overtime on Wednesdays...?!
 - Users are unable to request overtime on Saturdays
 - Users are unable to request overtime on Sundays until 11/24 (not shown on screenshot)

Here are the related configuration:
![image](https://user-images.githubusercontent.com/600347/66904078-ce67fb80-f003-11e9-82f3-d19bec8f345c.png)
![image](https://user-images.githubusercontent.com/600347/66904106-d889fa00-f003-11e9-98cd-3a0ed2ca40dd.png)

**Comment by polo2ro** [comment]
thanks for your report, there is a problem with select-able periods longer than one day, i am working on a solution

**Comment by polo2ro** [comment]
this commit is a fix for the week-end bug https://github.com/gadael/gadael/commit/756cac1b1a060d419fd4545b2394a8056e7d6b3a

there is still a problem with unavailable random days, i saw this on a sunday

**Comment by polo2ro** [comment]
fixed this in last version of https://github.com/polo2ro/teleperiod , version updated in dependencies
