### ISSUE TITLE
Can't Run Gadael

### ISSUE THREAD

**Issue by AchHam** [gadael/gadael#45]
when i run node app.js 3000 things won't work with this error message:

**DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.**

and the config.mongodb.init is set to false
![image](https://user-images.githubusercontent.com/48719886/77681224-5845c880-6f95-11ea-8497-bdc693c7571b.png)

**Comment by polo2ro** [comment]
the DeprecationWarning does not stop the server from running, this is just a warning

**Comment by AchHam** [comment]
thanks
